const DCAPI_ENDPOINT = process.env.NEXT_PUBLIC_DCAPI_ENDPOINT;
const DC_API_SEARCH_IIIF_URL = process.env.NEXT_PUBLIC_DC_API_SEARCH_IIIF_URL;
const DC_API_SEARCH_URL = `${DCAPI_ENDPOINT}/search`;

export { DCAPI_ENDPOINT, DC_API_SEARCH_IIIF_URL, DC_API_SEARCH_URL };
