import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "components/layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Home page</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <h1>Welcome to Next</h1>
      </div>
    </Layout>
  );
};

export default Home;
