import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "components/Layout";

const Search: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Home page</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
      </div>
    </Layout>
  );
};

export default Search;
