name: Run Unit Tests

on:
  push:
    branches:
      - "**" # This will run the action on push to any branch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_DCAPI_ENDPOINT: "https://dcapi.rdc-staging.library.northwestern.edu/api/v2"
      NEXT_PUBLIC_DC_URL: "https://dc-next.rdc-staging.library.northwestern.edu"

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Get files
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci --force

      - name: Run tests
        run: npm run test:ci
